// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicCarModel is the golang structure of table hg_basic_car_model for DAO operations like Where/Data.
type BasicCarModel struct {
	g.Meta        `orm:"table:hg_basic_car_model, do:true"`
	Id            interface{} //
	Code          interface{} // 车型编码
	Brand         interface{} // 品牌
	Cc            interface{} // 排量
	Year          interface{} // 年款
	Model         interface{} // 车型
	SaleName      interface{} // 销售名称
	Country       interface{} // 国家
	Type          interface{} // 国产合资进口
	Vender        interface{} // 厂家
	Fuel          interface{} // 燃油类型
	Gearbox       interface{} // 变速箱类型
	GearboxDesc   interface{} // 变速箱描述
	FrontTireSpec interface{} // 前轮胎规格
	BackTireSpec  interface{} // 后轮胎规格
	FrontHubSpec  interface{} // 前轮毂规格
	BackHubSpec   interface{} // 后轮毂规格
	Series        interface{} // 车系
	CreatedAt     *gtime.Time // 创建时间
	UpdatedAt     *gtime.Time // 更新时间
	CreatedById   interface{} // 创建用户的id
	UpdatedById   interface{} // 更新用户的id
	Deleted       interface{} // 是否标记删除
	Status        interface{} // 0启用1禁用
}
