// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicType is the golang structure of table hg_basic_type for DAO operations like Where/Data.
type BasicType struct {
	g.Meta    `orm:"table:hg_basic_type, do:true"`
	Id        interface{} // 类型ID
	Parent    interface{} // 父类型ID
	Name      interface{} // 类型名称
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	CreatedId interface{} //
	UpdatedId interface{} //
	Group     interface{} // 类型分组
}
