// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicCustomer is the golang structure of table hg_basic_customer for DAO operations like Where/Data.
type BasicCustomer struct {
	g.Meta      `orm:"table:hg_basic_customer, do:true"`
	Id          interface{} // 客户ID
	Type        interface{} // 客户类别-字典
	Name        interface{} // 客户名称
	Zjf         interface{} // 助记符
	Addr        interface{} // 客户地址
	Source      interface{} // 客户来源
	Supply      interface{} // 即是客户又是供应商
	Account     interface{} // 客户账户
	Certificate interface{} // 客户身份号码
	Code        interface{} // 客户编码
	ViteCode    interface{} // 邀请码
	Description interface{} // 描述
	Username    interface{} // 对账账号
	Password    interface{} // 对账密码
	CreatedAt   *gtime.Time // 创建时间
	UpdatedAt   *gtime.Time // 更新时间
	CreatedById interface{} // 创建用户的id
	UpdatedById interface{} // 更新用户的id
	Status      interface{} // 客户状态
	Contacts    *gjson.Json // 联系人
	Deleted     interface{} // 是否删除
	City        interface{} // 城市代码
}
