// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicCarInfo is the golang structure of table hg_basic_car_info for DAO operations like Where/Data.
type BasicCarInfo struct {
	g.Meta                 `orm:"table:hg_basic_car_info, do:true"`
	Id                     interface{} //
	Licence                interface{} // 车牌号
	Vin                    interface{} // VIN码
	CarId                  interface{} // 车型id
	EngineNo               interface{} // 发动机号
	CarCategory            interface{} // 上海车型分类
	UseType                interface{} // 使用性质
	FuelType               interface{} // 燃油类型
	ColorType              interface{} // 颜色类型
	CategoryCode           interface{} // 上海车型分类代码
	BuyDate                *gtime.Time // 购车日期
	EngineModel            interface{} // 发动机型号
	CustomerId             interface{} // 客户id
	DriverName             interface{} // 驾驶人姓名
	DriverPhone            interface{} // 驾驶人手机
	DriverTelephone        interface{} // 驾驶人电话
	DriverCertificate      interface{} // 驾驶人证件
	DriverDueDate          *gtime.Time // 驾照到期日
	DriverBirthday         interface{} // 驾驶人生日
	DriverLicensePhoto     interface{} // 驾驶证照片
	DriverVehiclePhoto     interface{} // 行驶证照片
	DriverCertificatePhoto interface{} // 身份证照片
	DriverInsurePhoto      interface{} // 车辆保险照片
	BuyCarPhoto            interface{} // 购车照片
	OtherPhoto             interface{} // 其他照片
	CreatedAt              *gtime.Time // 创建时间
	UpdatedAt              *gtime.Time // 更新时间
	CreatedById            interface{} // 创建用户的id
	UpdatedById            interface{} // 更新用户的id
	Deleted                interface{} // 是否标记删除
	Status                 interface{} // 0启用1禁用
}
