// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CustomerContact is the golang structure of table hg_customer_contact for DAO operations like Where/Data.
type CustomerContact struct {
	g.Meta      `orm:"table:hg_customer_contact, do:true"`
	Id          interface{} //
	Name        interface{} // 联系人
	Sex         interface{} // 性别
	CustomerId  interface{} // 客户id
	Phone       interface{} // 手机
	Telephone   interface{} // 座机
	Qq          interface{} // qq
	Wx          interface{} // 微信
	Birthday    *gtime.Time // 生日
	Email       interface{} // 邮箱
	Address     interface{} // 地址
	Openid      interface{} // 微信openid
	FirstChoose interface{} // 是否首选
}
