// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalBasicCarInfoDao is internal type for wrapping internal DAO implements.
type internalBasicCarInfoDao = *internal.BasicCarInfoDao

// basicCarInfoDao is the data access object for table hg_basic_car_info.
// You can define custom methods on it to extend its functionality as you wish.
type basicCarInfoDao struct {
	internalBasicCarInfoDao
}

var (
	// BasicCarInfo is globally public accessible object for table hg_basic_car_info operations.
	BasicCarInfo = basicCarInfoDao{
		internal.NewBasicCarInfoDao(),
	}
)

// Fill with you ideas below.
