// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalBasicCarModelDao is internal type for wrapping internal DAO implements.
type internalBasicCarModelDao = *internal.BasicCarModelDao

// basicCarModelDao is the data access object for table hg_basic_car_model.
// You can define custom methods on it to extend its functionality as you wish.
type basicCarModelDao struct {
	internalBasicCarModelDao
}

var (
	// BasicCarModel is globally public accessible object for table hg_basic_car_model operations.
	BasicCarModel = basicCarModelDao{
		internal.NewBasicCarModelDao(),
	}
)

// Fill with you ideas below.
