// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalBasicTypeDao is internal type for wrapping internal DAO implements.
type internalBasicTypeDao = *internal.BasicTypeDao

// basicTypeDao is the data access object for table hg_basic_type.
// You can define custom methods on it to extend its functionality as you wish.
type basicTypeDao struct {
	internalBasicTypeDao
}

var (
	// BasicType is globally public accessible object for table hg_basic_type operations.
	BasicType = basicTypeDao{
		internal.NewBasicTypeDao(),
	}
)

// Fill with you ideas below.
