// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalBasicCustomerDao is internal type for wrapping internal DAO implements.
type internalBasicCustomerDao = *internal.BasicCustomerDao

// basicCustomerDao is the data access object for table hg_basic_customer.
// You can define custom methods on it to extend its functionality as you wish.
type basicCustomerDao struct {
	internalBasicCustomerDao
}

var (
	// BasicCustomer is globally public accessible object for table hg_basic_customer operations.
	BasicCustomer = basicCustomerDao{
		internal.NewBasicCustomerDao(),
	}
)

// Fill with you ideas below.
