// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicCustomer is the golang structure for table basic_customer.
type BasicCustomer struct {
	Id          int64       `json:"id"          description:"客户ID"`
	Type        int64       `json:"type"        description:"客户类别-字典"`
	Name        string      `json:"name"        description:"客户名称"`
	Zjf         string      `json:"zjf"         description:"助记符"`
	Addr        string      `json:"addr"        description:"客户地址"`
	Source      int64       `json:"source"      description:"客户来源"`
	Supply      int         `json:"supply"      description:"即是客户又是供应商"`
	Account     string      `json:"account"     description:"客户账户"`
	Certificate string      `json:"certificate" description:"客户身份号码"`
	Code        string      `json:"code"        description:"客户编码"`
	ViteCode    string      `json:"viteCode"    description:"邀请码"`
	Description string      `json:"description" description:"描述"`
	Username    string      `json:"username"    description:"对账账号"`
	Password    string      `json:"password"    description:"对账密码"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:"创建时间"`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:"更新时间"`
	CreatedById int64       `json:"createdById" description:"创建用户的id"`
	UpdatedById int64       `json:"updatedById" description:"更新用户的id"`
	Status      int         `json:"status"      description:"客户状态"`
	Contacts    *gjson.Json `json:"contacts"    description:"联系人"`
	Deleted     uint        `json:"deleted"     description:"是否删除"`
	City        int64       `json:"city"        description:"城市代码"`
}
