// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicCarInfo is the golang structure for table basic_car_info.
type BasicCarInfo struct {
	Id                     int64       `json:"id"                     description:""`
	Licence                string      `json:"licence"                description:"车牌号"`
	Vin                    string      `json:"vin"                    description:"VIN码"`
	CarId                  int64       `json:"carId"                  description:"车型id"`
	EngineNo               string      `json:"engineNo"               description:"发动机号"`
	CarCategory            int         `json:"carCategory"            description:"上海车型分类"`
	UseType                int         `json:"useType"                description:"使用性质"`
	FuelType               int         `json:"fuelType"               description:"燃油类型"`
	ColorType              uint        `json:"colorType"              description:"颜色类型"`
	CategoryCode           string      `json:"categoryCode"           description:"上海车型分类代码"`
	BuyDate                *gtime.Time `json:"buyDate"                description:"购车日期"`
	EngineModel            string      `json:"engineModel"            description:"发动机型号"`
	CustomerId             int64       `json:"customerId"             description:"客户id"`
	DriverName             string      `json:"driverName"             description:"驾驶人姓名"`
	DriverPhone            string      `json:"driverPhone"            description:"驾驶人手机"`
	DriverTelephone        string      `json:"driverTelephone"        description:"驾驶人电话"`
	DriverCertificate      string      `json:"driverCertificate"      description:"驾驶人证件"`
	DriverDueDate          *gtime.Time `json:"driverDueDate"          description:"驾照到期日"`
	DriverBirthday         string      `json:"driverBirthday"         description:"驾驶人生日"`
	DriverLicensePhoto     string      `json:"driverLicensePhoto"     description:"驾驶证照片"`
	DriverVehiclePhoto     string      `json:"driverVehiclePhoto"     description:"行驶证照片"`
	DriverCertificatePhoto string      `json:"driverCertificatePhoto" description:"身份证照片"`
	DriverInsurePhoto      string      `json:"driverInsurePhoto"      description:"车辆保险照片"`
	BuyCarPhoto            string      `json:"buyCarPhoto"            description:"购车照片"`
	OtherPhoto             string      `json:"otherPhoto"             description:"其他照片"`
	CreatedAt              *gtime.Time `json:"createdAt"              description:"创建时间"`
	UpdatedAt              *gtime.Time `json:"updatedAt"              description:"更新时间"`
	CreatedById            int64       `json:"createdById"            description:"创建用户的id"`
	UpdatedById            int64       `json:"updatedById"            description:"更新用户的id"`
	Deleted                uint        `json:"deleted"                description:"是否标记删除"`
	Status                 uint        `json:"status"                 description:"0启用1禁用"`
}
