// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicCarModel is the golang structure for table basic_car_model.
type BasicCarModel struct {
	Id            int64       `json:"id"            description:""`
	Code          string      `json:"code"          description:"车型编码"`
	Brand         string      `json:"brand"         description:"品牌"`
	Cc            string      `json:"cc"            description:"排量"`
	Year          int         `json:"year"          description:"年款"`
	Model         string      `json:"model"         description:"车型"`
	SaleName      string      `json:"saleName"      description:"销售名称"`
	Country       string      `json:"country"       description:"国家"`
	Type          uint        `json:"type"          description:"国产合资进口"`
	Vender        string      `json:"vender"        description:"厂家"`
	Fuel          int         `json:"fuel"          description:"燃油类型"`
	Gearbox       int         `json:"gearbox"       description:"变速箱类型"`
	GearboxDesc   string      `json:"gearboxDesc"   description:"变速箱描述"`
	FrontTireSpec int         `json:"frontTireSpec" description:"前轮胎规格"`
	BackTireSpec  int         `json:"backTireSpec"  description:"后轮胎规格"`
	FrontHubSpec  int         `json:"frontHubSpec"  description:"前轮毂规格"`
	BackHubSpec   int         `json:"backHubSpec"   description:"后轮毂规格"`
	Series        string      `json:"series"        description:"车系"`
	CreatedAt     *gtime.Time `json:"createdAt"     description:"创建时间"`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:"更新时间"`
	CreatedById   int64       `json:"createdById"   description:"创建用户的id"`
	UpdatedById   int64       `json:"updatedById"   description:"更新用户的id"`
	Deleted       uint        `json:"deleted"       description:"是否标记删除"`
	Status        uint        `json:"status"        description:"0启用1禁用"`
}
