// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BasicType is the golang structure for table basic_type.
type BasicType struct {
	Id        int         `json:"id"        description:"类型ID"`
	Parent    int         `json:"parent"    description:"父类型ID"`
	Name      string      `json:"name"      description:"类型名称"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	CreatedId int         `json:"createdId" description:""`
	UpdatedId int         `json:"updatedId" description:""`
	Group     string      `json:"group"     description:"类型分组"`
}
